
<!DOCTYPE html>
<html>
    <head>
        <title> Test JS MVC App </title>
        <!-- JS Libraries -->
        <script src="/js/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script src="/js/underscore.js" type="text/javascript"></script>
        <script src="/js/json2.js" type="text/javascript"></script>
        <script src="/js/backbone.js" type="text/javascript"></script>
        <?php
        echo $this->jQuery();
        echo $this->headLink();        
        ?>
    </head>
    <body><?php echo $this->layout()->content; ?></body>
</html>