
<!DOCTYPE html>
<html>
    <head>
        <title> Test JS MVC App </title>
        <!-- Styles -->
        <link rel="stylesheet" type="text/css" href="/css/themes/blitzer/jquery-ui-1.8.18.custom.css" />
        <!-- JS Libraries -->
        <script src="/js/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script src="/js/underscore.js" type="text/javascript"></script>
        <script src="/js/json2.js" type="text/javascript"></script>
        <script src="/js/backbone.js" type="text/javascript"></script>
        <?php
        echo $this->jQuery();
        echo $this->headLink();        
        ?>
    </head>
    <body><?php echo $this->layout()->content; ?></body>
</html>